const lessonType = {
  lecture: 'Лекция',
  practice: 'Практика',
  laba: 'Лаба',
};

const teachers = {
  Pitsuha: 'Пицуха Е.А.',
  Nemkevich: 'Немкевич Е.Г',
  Krutilin: 'Крутилин А.Б.',
  Nekalo: 'Некало И.А.',
  Svistun: 'Свистун А.Л.',
  Brakovich: 'Бракович И.С.',
  Dyachek: 'Дячек П.И',
  Livansky: 'Ливанский Д.Г.',
  Polyakova: 'Полякова О.Е.',
  Strytsky: 'Струцкий Н.В',
  Volohovich: 'Волохович Д.А.',
  Karnytsky: 'Карницкий Н.Б.',
};

const subjects = {
  teplustanovki: {
    shortName: 'Тепл. установки',
    name: 'Теплогенерирующие установки',
  },
  infchas: {
    shortName: 'Инф. час',
    name: 'Информационный / Кураторский час',
  },
  ouis: {
    shortName: 'ОУИС',
    name: 'Основы управления интеллектуальной собственностью',
  },
  stroyteplfiz: {
    shortName: 'Стр. теплофизика',
    name: 'Строительная теплофизика',
  },
  teplogenustanovki: {
    shortName: 'Теплоген. установки',
    name: 'Теплогенерирующие установки',
  },
  teplomasobmen: {
    shortName: 'Тепломассообмен',
    name: 'Тепломассообмен',
  },
  engecology: {
    shortName: 'Инж. экология',
    name: 'Инженерная экология',
  },
  nvik: {
    shortName: 'НВиК',
    name: 'Насосы, вентиляторы и компрессоры',
  },
  otoplenie: {
    shortName: 'Отопление',
    name: 'Отопление',
  },
  vodosnabjenie: {
    shortName: 'Водоснабжение',
    name: 'Водоснабжение и водоотведение',
  },
  fizra: {
    shortName: 'Физра',
    name: 'Физическая культура',
  },
};

export const bntuSchedule = {
  group11004122: {
    monday: [
      {
        id: 1,
        startTime: '8:00',
        endTime: '9:35',
        type: lessonType.practice,
        shortName: subjects.engecology.shortName,
        name: subjects.engecology.name,
        teacher: teachers.Brakovich,
        class: '410',
        korpus: '11А',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 2,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.lecture,
        shortName: subjects.teplogenustanovki.shortName,
        name: subjects.teplogenustanovki.name,
        teacher: teachers.Pitsuha,
        class: '3П',
        korpus: '8',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 3,
        startTime: '10:40',
        endTime: '13:15',
        type: lessonType.practice,
        shortName: subjects.infchas.shortName,
        name: subjects.infchas.name,
        teacher: '',
        class: '21',
        korpus: '1',
        subgroup: '0',
        week: ['1'],
      },
      {
        id: 4,
        startTime: '13:55',
        endTime: '15:30',
        type: lessonType.practice,
        shortName: subjects.ouis.shortName,
        name: subjects.ouis.name,
        teacher: teachers.Nemkevich,
        class: '24',
        korpus: '1',
        subgroup: '0',
        week: ['1'],
      },
    ],
    tuesday: [
      {
        id: 1,
        startTime: '8:00',
        endTime: '9:35',
        type: lessonType.lecture,
        shortName: subjects.stroyteplfiz.shortName,
        name: subjects.stroyteplfiz.name,
        teacher: teachers.Krutilin,
        class: '339',
        korpus: '1',
        subgroup: '0',
        week: ['1'],
      },
      {
        id: 2,
        startTime: '8:00',
        endTime: '9:35',
        type: lessonType.lecture,
        shortName: subjects.otoplenie.shortName,
        name: subjects.otoplenie.name,
        teacher: teachers.Livansky,
        class: '339',
        korpus: '1',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 3,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.teplogenustanovki.shortName,
        name: subjects.teplogenustanovki.name,
        teacher: teachers.Nekalo,
        class: '322',
        korpus: '2',
        subgroup: '2',
        week: ['1'],
      },
      {
        id: 4,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.teplogenustanovki.shortName,
        name: subjects.teplogenustanovki.name,
        teacher: teachers.Nekalo,
        class: '322',
        korpus: '2',
        subgroup: '1',
        week: ['2'],
      },
      {
        id: 5,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.teplomasobmen.shortName,
        name: subjects.teplomasobmen.name,
        teacher: teachers.Svistun,
        class: '14',
        korpus: '1',
        subgroup: '1',
        week: ['1'],
      },
      {
        id: 6,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.teplomasobmen.shortName,
        name: subjects.teplomasobmen.name,
        teacher: teachers.Svistun,
        class: '14',
        korpus: '1',
        subgroup: '2',
        week: ['2'],
      },
      {
        id: 7,
        startTime: '10:40',
        endTime: '13:15',
        type: lessonType.practice,
        shortName: subjects.infchas.shortName,
        name: subjects.infchas.name,
        teacher: '',
        class: '362',
        korpus: '1',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 8,
        startTime: '13:55',
        endTime: '15:30',
        type: lessonType.practice,
        shortName: subjects.ouis.shortName,
        name: subjects.ouis.name,
        teacher: teachers.Nemkevich,
        class: '339',
        korpus: '1',
        subgroup: '0',
        week: ['2'],
      },
    ],
    wednesday: [
      {
        id: 1,
        startTime: '8:00',
        endTime: '9:35',
        type: lessonType.practice,
        shortName: subjects.teplomasobmen.shortName,
        name: subjects.teplomasobmen.name,
        teacher: teachers.Svistun,
        class: '21',
        korpus: '1',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 2,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.stroyteplfiz.shortName,
        name: subjects.stroyteplfiz.name,
        teacher: teachers.Krutilin,
        class: '14',
        korpus: '1',
        subgroup: '1',
        week: ['1'],
      },
      {
        id: 3,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.stroyteplfiz.shortName,
        name: subjects.stroyteplfiz.name,
        teacher: teachers.Krutilin,
        class: '14',
        korpus: '1',
        subgroup: '1',
        week: ['2'],
      },
      {
        id: 4,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.nvik.shortName,
        name: subjects.nvik.name,
        teacher: teachers.Dyachek,
        class: '21',
        korpus: '1',
        subgroup: '2',
        week: ['2'],
      },
      {
        id: 5,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.laba,
        shortName: subjects.nvik.shortName,
        name: subjects.nvik.name,
        teacher: teachers.Dyachek,
        class: '21',
        korpus: '1',
        subgroup: '2',
        week: ['1'],
      },
      {
        id: 6,
        startTime: '10:40',
        endTime: '13:15',
        type: lessonType.practice,
        shortName: subjects.teplogenustanovki.shortName,
        name: subjects.teplogenustanovki.name,
        teacher: teachers.Karnytsky,
        class: '322',
        korpus: '2',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 7,
        startTime: '13:55',
        endTime: '15:30',
        type: lessonType.practice,
        shortName: subjects.stroyteplfiz.shortName,
        name: subjects.stroyteplfiz.name,
        teacher: teachers.Krutilin,
        class: '312',
        korpus: '9',
        subgroup: '0',
        week: ['2'],
      },
    ],
    thursday: [
      {
        id: 1,
        startTime: '8:00',
        endTime: '9:35',
        type: lessonType.lecture,
        shortName: subjects.otoplenie.shortName,
        name: subjects.otoplenie.name,
        teacher: teachers.Livansky,
        class: '447',
        korpus: '1',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 2,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.practice,
        shortName: subjects.fizra.shortName,
        name: subjects.fizra.name,
        teacher: '',
        class: '',
        korpus: '',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 3,
        startTime: '10:40',
        endTime: '13:15',
        type: lessonType.lecture,
        shortName: subjects.stroyteplfiz.shortName,
        name: subjects.stroyteplfiz.name,
        teacher: teachers.Krutilin,
        class: '4П',
        korpus: '8',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 4,
        startTime: '13:55',
        endTime: '15:30',
        type: lessonType.lecture,
        shortName: subjects.nvik.shortName,
        name: subjects.nvik.name,
        teacher: teachers.Dyachek,
        class: '5П',
        korpus: '8',
        subgroup: '0',
        week: ['1', '2'],
      },
    ],
    friday: [
      {
        id: 1,
        startTime: '8:00',
        endTime: '9:35',
        type: lessonType.lecture,
        shortName: subjects.vodosnabjenie.shortName,
        name: subjects.vodosnabjenie.name,
        teacher: teachers.Polyakova,
        class: '419',
        korpus: '1',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 2,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.practice,
        shortName: subjects.vodosnabjenie.shortName,
        name: subjects.vodosnabjenie.name,
        teacher: teachers.Polyakova,
        class: '14',
        korpus: '1',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 3,
        startTime: '13:55',
        endTime: '15:30',
        type: lessonType.lecture,
        shortName: subjects.engecology.shortName,
        name: subjects.engecology.name,
        teacher: teachers.Brakovich,
        class: '5П',
        korpus: '8',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 4,
        startTime: '15:40',
        endTime: '17:15',
        type: lessonType.practice,
        shortName: subjects.fizra.shortName,
        name: subjects.fizra.name,
        teacher: '',
        class: '',
        korpus: '',
        subgroup: '0',
        week: ['1', '2'],
      },
    ],
    saturday: [
      {
        id: 1,
        startTime: '8:00',
        endTime: '9:35',
        type: lessonType.lecture,
        shortName: subjects.teplomasobmen.shortName,
        name: subjects.teplomasobmen.name,
        teacher: teachers.Strytsky,
        class: '453',
        korpus: '1',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 2,
        startTime: '9:55',
        endTime: '10:30',
        type: lessonType.lecture,
        shortName: subjects.teplomasobmen.shortName,
        name: subjects.teplomasobmen.name,
        teacher: teachers.Strytsky,
        class: '453',
        korpus: '1',
        subgroup: '0',
        week: ['1', '2'],
      },
      {
        id: 3,
        startTime: '10:40',
        endTime: '13:15',
        type: lessonType.practice,
        shortName: subjects.otoplenie.shortName,
        name: subjects.otoplenie.name,
        teacher: teachers.Volohovich,
        class: '21',
        korpus: '1',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 4,
        startTime: '15:40',
        endTime: '17:15',
        type: lessonType.laba,
        shortName: subjects.otoplenie.shortName,
        name: subjects.otoplenie.name,
        teacher: teachers.Volohovich,
        class: '9',
        korpus: '1',
        subgroup: '0',
        week: ['1'],
      },
      {
        id: 5,
        startTime: '15:40',
        endTime: '17:15',
        type: lessonType.laba,
        shortName: subjects.otoplenie.shortName,
        name: subjects.otoplenie.name,
        teacher: teachers.Volohovich,
        class: '9',
        korpus: '1',
        subgroup: '1',
        week: ['1'],
      },
      {
        id: 6,
        startTime: '15:40',
        endTime: '17:15',
        type: lessonType.laba,
        shortName: subjects.otoplenie.shortName,
        name: subjects.otoplenie.name,
        teacher: teachers.Volohovich,
        class: '9',
        korpus: '1',
        subgroup: '2',
        week: ['2'],
      },
    ],
  },
};
