const lessonType = {
  lecture: 'Лекция',
  practice: 'Практика',
  laba: 'Лаба',
};

const teachers = {
  Ponomareva: 'Пономарева Е.И.',
  Pinchuk: 'Пинчук Т.Г.',
  Rusakovich: 'Русакович А.Н.',
  Artyshevsky: 'Артюшевский Н.В.',
  Storozhev: 'Сторожев Д.А.',
  PetrovichUU: 'Петрович Ю.Ю.',
  Parhimenko: 'Пархименко В.А.',
  Shevaldisheva: 'Шевалдышева Е.З.',
  Pashkovskaya: 'Пашковская К.В.',
  Tkalich: 'Ткалич Т.А',
  Smirnov: 'Смирнов И.В.',
  Komlichenko: 'Компличенко В.Н.',
  Nagulevich: 'Нагулевич Р.С.',
  Nicheporuk: 'Ничепорук В.В.',
  Primakovich: 'Компличенко В.Н.',
  Matyas: 'Матяс О.А.',
  Dobish: 'Добыш М.А.',
};

const subjects = {
  ris: {
    shortName: 'РИС',
    name: 'Распределенные информационные системы',
  },
  iove: {
    shortName: 'ИОвЭ',
    name: 'Исследование операций в экономике',
  },
  mrcb: {
    shortName: 'МРЦБ',
    name: 'Моделирование рынка ценных бумаг',
  },
  stoei: {
    shortName: 'СТОЭИ',
    name: 'Современные технологии обработки экономической информации',
  },
  simubd: {
    shortName: 'СиМУБД',
    name: 'Системы и методы управления базами данных',
  },
  iitem: {
    shortName: 'ИиТЭМ',
    name: 'Инструменты и технологии электронного маркетинга',
  },
  do: {
    shortName: 'ДО',
    name: 'Деловое общение',
  },
  infsup: {
    shortName: 'ИнфСУП',
    name: 'Информационные системы управления предприятием',
  },
  otoplenie: {
    shortName: 'Отопление',
    name: 'Отопление',
  },
  vodosnabjenie: {
    shortName: 'Водоснабжение',
    name: 'Водоснабжение и водоотведение',
  },
  fizra: {
    shortName: 'Физра',
    name: 'Физическая культура',
  },
  buaia: {
    shortName: 'БУАиА',
    name: 'Бухгалтерский учет, анализ и аудит',
  },
};

export const bsuirSchedule = {
  group172301: {
    monday: [
      {
        id: 1,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.laba,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Ponomareva,
        class: '902',
        korpus: '5',
        subgroup: '2',
        week: ['3'],
      },
      {
        id: 2,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.laba,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Ponomareva,
        class: '902',
        korpus: '5',
        subgroup: '1',
        week: ['1'],
      },
      {
        id: 3,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.lecture,
        shortName: subjects.iove.shortName,
        name: subjects.iove.name,
        teacher: teachers.Pinchuk,
        class: '712',
        korpus: '5',
        subgroup: '0',
        week: ['1', '3'],
      },
      {
        id: 4,
        startTime: '17:25',
        endTime: '18:45',
        type: lessonType.lecture,
        shortName: subjects.mrcb.shortName,
        name: subjects.mrcb.name,
        teacher: teachers.Pinchuk,
        class: '514',
        korpus: '5',
        subgroup: '0',
        week: ['2', '4'],
      },
      {
        id: 5,
        startTime: '17:25',
        endTime: '18:45',
        type: lessonType.lecture,
        shortName: subjects.stoei.shortName,
        name: subjects.stoei.name,
        teacher: teachers.Rusakovich,
        class: '514',
        korpus: '5',
        subgroup: '0',
        week: ['1', '3'],
      },
      {
        id: 6,
        startTime: '19:00',
        endTime: '20:20',
        type: lessonType.lecture,
        shortName: subjects.simubd.shortName,
        name: subjects.simubd.name,
        teacher: teachers.Storozhev,
        class: '514',
        korpus: '5',
        subgroup: '0',
        week: ['2', '4'],
      },
    ],
    tuesday: [
      {
        id: 1,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.laba,
        shortName: subjects.stoei.shortName,
        name: subjects.stoei.name,
        teacher: teachers.PetrovichUU,
        class: '318а',
        korpus: '5',
        subgroup: '1',
        week: ['2'],
      },
      {
        id: 2,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.laba,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Ponomareva,
        class: '322б',
        korpus: '5',
        subgroup: '1',
        week: ['3'],
      },
      {
        id: 3,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.laba,
        shortName: subjects.stoei.shortName,
        name: subjects.stoei.name,
        teacher: teachers.PetrovichUU,
        class: '309',
        korpus: '5',
        subgroup: '2',
        week: ['3'],
      },
      {
        id: 4,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.laba,
        shortName: subjects.stoei.shortName,
        name: subjects.stoei.name,
        teacher: teachers.PetrovichUU,
        class: '318а',
        korpus: '5',
        subgroup: '2',
        week: ['4'],
      },
      {
        id: 5,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.laba,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Ponomareva,
        class: '322б',
        korpus: '5',
        subgroup: '2',
        week: ['1'],
      },
      {
        id: 6,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.laba,
        shortName: subjects.stoei.shortName,
        name: subjects.stoei.name,
        teacher: teachers.PetrovichUU,
        class: '309',
        korpus: '5',
        subgroup: '1',
        week: ['1'],
      },
      {
        id: 7,
        startTime: '17:25',
        endTime: '18:45',
        type: lessonType.lecture,
        shortName: subjects.iitem.shortName,
        name: subjects.iitem.name,
        teacher: teachers.Parhimenko,
        class: '209',
        korpus: '4',
        subgroup: '0',
        week: ['1', '2', '3', '4'],
      },
      {
        id: 8,
        startTime: '19:00',
        endTime: '20:20',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Shevaldisheva,
        class: '402',
        korpus: '4',
        subgroup: '2',
        week: ['1', '2', '3', '4'],
      },
      {
        id: 9,
        startTime: '19:00',
        endTime: '20:20',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Pashkovskaya,
        class: '400',
        korpus: '4',
        subgroup: '1',
        week: ['1', '2', '3', '4'],
      },
      {
        id: 10,
        startTime: '20:40',
        endTime: '22:00',
        type: lessonType.lecture,
        shortName: subjects.infsup.shortName,
        name: subjects.infsup.name,
        teacher: teachers.Tkalich,
        class: '214',
        korpus: '4',
        subgroup: '0',
        week: ['2', '4'],
      },
      {
        id: 11,
        startTime: '20:20',
        endTime: '22:40',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Pashkovskaya,
        class: '402',
        korpus: '4',
        subgroup: '2',
        week: ['1', '3'],
      },
      {
        id: 12,
        startTime: '20:20',
        endTime: '22:00',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Pashkovskaya,
        class: '400',
        korpus: '4',
        subgroup: '1',
        week: ['1', '3'],
      },
    ],
    wednesday: [
      {
        id: 1,
        startTime: '12:25',
        endTime: '13:45',
        type: lessonType.lecture,
        shortName: subjects.buaia.shortName,
        name: subjects.buaia.name,
        teacher: teachers.Smirnov,
        class: '712',
        korpus: '5',
        subgroup: '0',
        week: ['1', '2', '3'],
      },
      {
        id: 2,
        startTime: '12:25',
        endTime: '13:45',
        type: lessonType.lecture,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Komlichenko,
        class: '712',
        korpus: '5',
        subgroup: '0',
        week: ['4'],
      },
      {
        id: 3,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.lecture,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Komlichenko,
        class: '712',
        korpus: '5',
        subgroup: '0',
        week: ['1', '2', '4'],
      },
      {
        id: 4,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.lecture,
        shortName: subjects.iove.shortName,
        name: subjects.iove.name,
        teacher: teachers.Pinchuk,
        class: '712',
        korpus: '5',
        subgroup: '0',
        week: ['3'],
      },
      {
        id: 5,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.practice,
        shortName: subjects.infsup.shortName,
        name: subjects.infsup.name,
        teacher: teachers.PetrovichUU,
        class: '410а',
        korpus: '4',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 6,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.practice,
        shortName: subjects.infsup.shortName,
        name: subjects.infsup.name,
        teacher: teachers.PetrovichUU,
        class: '902',
        korpus: '5',
        subgroup: '0',
        week: ['1', '3'],
      },
      {
        id: 7,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Pashkovskaya,
        class: '417',
        korpus: '4',
        subgroup: '1',
        week: ['4'],
      },
      {
        id: 8,
        startTime: '17:25',
        endTime: '18:45',
        type: lessonType.practice,
        shortName: subjects.mrcb.shortName,
        name: subjects.mrcb.name,
        teacher: teachers.Nagulevich,
        class: '514',
        korpus: '4',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 9,
        startTime: '17:25',
        endTime: '18:45',
        type: lessonType.laba,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Ponomareva,
        class: '514',
        korpus: '4',
        subgroup: '2',
        week: ['3'],
      },
      {
        id: 10,
        startTime: '17:25',
        endTime: '18:45',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Pashkovskaya,
        class: '409',
        korpus: '5',
        subgroup: '1',
        week: ['4'],
      },
      {
        id: 11,
        startTime: '17:25',
        endTime: '18:45',
        type: lessonType.laba,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Ponomareva,
        class: '514',
        korpus: '4',
        subgroup: '1',
        week: ['1'],
      },
    ],
    thursday: [
      {
        id: 1,
        startTime: '10:35',
        endTime: '11:55',
        type: lessonType.laba,
        shortName: subjects.stoei.shortName,
        name: subjects.stoei.name,
        teacher: teachers.PetrovichUU,
        class: '318',
        korpus: '4',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 2,
        startTime: '12:25',
        endTime: '13:45',
        type: lessonType.laba,
        shortName: subjects.ris.shortName,
        name: subjects.ris.name,
        teacher: teachers.Ponomareva,
        class: '322б',
        korpus: '5',
        subgroup: '0',
        week: ['2', '4'],
      },
      {
        id: 3,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.practice,
        shortName: subjects.iove.shortName,
        name: subjects.iove.name,
        teacher: teachers.Nicheporuk,
        class: '417',
        korpus: '4',
        subgroup: '0',
        week: ['2', '4'],
      },
      {
        id: 4,
        startTime: '15:50',
        endTime: '17:10',
        type: lessonType.practice,
        shortName: subjects.iove.shortName,
        name: subjects.iove.name,
        teacher: teachers.Nicheporuk,
        class: '417',
        korpus: '4',
        subgroup: '0',
        week: ['2', '4'],
      },
    ],
    friday: [
      {
        id: 1,
        startTime: '12:25',
        endTime: '13:45',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Shevaldisheva,
        class: '413',
        korpus: '4',
        subgroup: '2',
        week: ['4'],
      },
      {
        id: 2,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.practice,
        shortName: subjects.do.shortName,
        name: subjects.do.name,
        teacher: teachers.Shevaldisheva,
        class: '413',
        korpus: '4',
        subgroup: '2',
        week: ['4'],
      },
    ],
    saturday: [
      {
        id: 1,
        startTime: '09:00',
        endTime: '10:20',
        type: lessonType.laba,
        shortName: subjects.simubd.shortName,
        name: subjects.simubd.name,
        teacher: teachers.Primakovich,
        class: '310к',
        korpus: '4',
        subgroup: '1',
        week: ['2'],
      },
      {
        id: 2,
        startTime: '09:00',
        endTime: '10:20',
        type: lessonType.laba,
        shortName: subjects.simubd.shortName,
        name: subjects.simubd.name,
        teacher: teachers.Primakovich,
        class: '310а',
        korpus: '4',
        subgroup: '2',
        week: ['4'],
      },
      {
        id: 3,
        startTime: '10:35',
        endTime: '11:55',
        type: lessonType.laba,
        shortName: subjects.buaia.shortName,
        name: subjects.buaia.name,
        teacher: teachers.Matyas,
        class: '221',
        korpus: '5',
        subgroup: '1',
        week: ['2'],
      },
      {
        id: 4,
        startTime: '10:35',
        endTime: '11:55',
        type: lessonType.laba,
        shortName: subjects.simubd.shortName,
        name: subjects.simubd.name,
        teacher: teachers.Primakovich,
        class: '310а',
        korpus: '4',
        subgroup: '2',
        week: ['2'],
      },
      {
        id: 5,
        startTime: '10:35',
        endTime: '11:55',
        type: lessonType.laba,
        shortName: subjects.buaia.shortName,
        name: subjects.buaia.name,
        teacher: teachers.Matyas,
        class: '414',
        korpus: '4',
        subgroup: '0',
        week: ['3'],
      },
      {
        id: 6,
        startTime: '10:35',
        endTime: '11:55',
        type: lessonType.laba,
        shortName: subjects.buaia.shortName,
        name: subjects.buaia.name,
        teacher: teachers.Matyas,
        class: '514',
        korpus: '4',
        subgroup: '2',
        week: ['4'],
      },
      {
        id: 7,
        startTime: '10:35',
        endTime: '11:55',
        type: lessonType.laba,
        shortName: subjects.simubd.shortName,
        name: subjects.simubd.name,
        teacher: teachers.Primakovich,
        class: '310а',
        korpus: '4',
        subgroup: '1',
        week: ['4'],
      },
      {
        id: 8,
        startTime: '12:25',
        endTime: '13:45',
        type: lessonType.practice,
        shortName: subjects.mrcb.shortName,
        name: subjects.mrcb.name,
        teacher: teachers.Nagulevich,
        class: '310а',
        korpus: '4',
        subgroup: '0',
        week: ['2'],
      },
      {
        id: 9,
        startTime: '12:25',
        endTime: '13:45',
        type: lessonType.lecture,
        shortName: subjects.iove.shortName,
        name: subjects.iove.name,
        teacher: teachers.Pinchuk,
        class: '712',
        korpus: '5',
        subgroup: '0',
        week: ['1', '3'],
      },
      {
        id: 10,
        startTime: '12:25',
        endTime: '13:45',
        type: lessonType.laba,
        shortName: subjects.simubd.shortName,
        name: subjects.simubd.name,
        teacher: teachers.Primakovich,
        class: '310а',
        korpus: '4',
        subgroup: '0',
        week: ['4'],
      },
      {
        id: 11,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.practice,
        shortName: subjects.iitem.shortName,
        name: subjects.iitem.name,
        teacher: teachers.Dobish,
        class: '901',
        korpus: '5',
        subgroup: '0',
        week: ['2', '4'],
      },
      {
        id: 12,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.lecture,
        shortName: subjects.mrcb.shortName,
        name: subjects.mrcb.name,
        teacher: teachers.Pinchuk,
        class: '209',
        korpus: '4',
        subgroup: '0',
        week: ['3'],
      },
      {
        id: 11,
        startTime: '14:00',
        endTime: '15:20',
        type: lessonType.lecture,
        shortName: subjects.iove.shortName,
        name: subjects.iove.name,
        teacher: teachers.Pinchuk,
        class: '712',
        korpus: '5',
        subgroup: '0',
        week: ['1'],
      },
    ],
    sunday: [],
  },
};
