const lessonType = {
  lecture: 'Лекция',
  practice: 'Практика',
  laba: 'Лаба',
};

const teachers = {
  Petsuha: 'Пецуха Е.А.',
  Nemkevich: 'Немкевич Е.Г',
  Krutilin: 'Крутилин А.Б.',
  Nekalo: 'Некало И.А.',
  Svistun: 'Свистун А.Л.',
  Brakovich: 'Бракович И.С.',
  Dyachek: 'Дячек П.И',
  Livansky: 'Ливанский Д.Г.',
  Polyakova: 'Полякова О.Е.',
  Strytsky: 'Струцкий Н.В',
  Volohovich: 'Волохович Д.А.',
  Karnytsky: 'Карницкий Н.Б.',
};

const subjects = {
  teplustanovki: {
    shortName: 'Тепл. установки',
    name: 'Теплогенерирующие установки',
  },
  infchas: {
    shortName: 'Инф. час',
    name: 'Информационный / Кураторский час',
  },
  ouis: {
    shortName: 'ОУИС',
    name: 'Основы управления интеллектуальной собственностью',
  },
  stroyteplfiz: {
    shortName: 'Стр. теплофизика',
    name: 'Строительная теплофизика',
  },
  teplogenustanovki: {
    shortName: 'Теплоген. установки',
    name: 'Теплогенерирующие установки',
  },
  teplomasobmen: {
    shortName: 'Тепломассообмен',
    name: 'Тепломассообмен',
  },
  engecology: {
    shortName: 'Инж. экология',
    name: 'Инженерная экология',
  },
  nvik: {
    shortName: 'НВиК',
    name: 'Насосы, вентиляторы и компрессоры',
  },
  otoplenie: {
    shortName: 'Отопление',
    name: 'Отопление',
  },
  vodosnabjenie: {
    shortName: 'Водоснабжение',
    name: 'Водоснабжение и водоотведение',
  },
  fizra: {
    shortName: 'Физра',
    name: 'Физическая культура',
  },
  tgu: {
    shortName: 'ТГУ',
    name: '',
  },
};

export interface DaySchedule {
  id: number;
  startTime: string;
  endTime: string;
  type: string;
  shortName: string;
  name: string;
  teacher: string;
  class: string;
  korpus: string;
  subgroup: string;
}
export const schedule = {
  group11004122: {
    week1: {
      monday: [
        {
          id: 1,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.lecture,
          shortName: subjects.teplustanovki.shortName,
          name: subjects.teplustanovki.name,
          teacher: teachers.Petsuha,
          class: '3П',
          korpus: '8',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.practice,
          shortName: subjects.infchas.shortName,
          name: subjects.infchas.name,
          teacher: '',
          class: '21',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 3,
          startTime: '13:55',
          endTime: '15:30',
          type: lessonType.practice,
          shortName: subjects.ouis.shortName,
          name: subjects.ouis.name,
          teacher: teachers.Nemkevich,
          class: '24',
          korpus: '1',
          subgroup: '0',
        },
      ],
      tuesday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.stroyteplfiz.shortName,
          name: subjects.stroyteplfiz.name,
          teacher: teachers.Krutilin,
          class: '339',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.teplogenustanovki.shortName,
          name: subjects.teplogenustanovki.name,
          teacher: teachers.Nekalo,
          class: '322',
          korpus: '2',
          subgroup: '1',
        },
        {
          id: 3,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.teplomasobmen.shortName,
          name: subjects.teplomasobmen.name,
          teacher: teachers.Svistun,
          class: '322',
          korpus: '2',
          subgroup: '2',
        },
        {
          id: 4,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.practice,
          shortName: subjects.engecology.shortName,
          name: subjects.engecology.name,
          teacher: teachers.Brakovich,
          class: '24',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 5,
          startTime: '13:55',
          endTime: '15:30',
          type: lessonType.practice,
          shortName: subjects.engecology.shortName,
          name: subjects.engecology.name,
          teacher: teachers.Brakovich,
          class: '24',
          korpus: '1',
          subgroup: '0',
        },
      ],
      wednesday: [
        {
          id: 1,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.stroyteplfiz.shortName,
          name: subjects.stroyteplfiz.name,
          teacher: teachers.Krutilin,
          class: '14',
          korpus: '1',
          subgroup: '1',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.nvik.shortName,
          name: subjects.nvik.name,
          teacher: teachers.Dyachek,
          class: '24',
          korpus: '1',
          subgroup: '2',
        },
      ],
      thursday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.otoplenie.shortName,
          name: subjects.otoplenie.name,
          teacher: teachers.Livansky,
          class: '447',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.lecture,
          shortName: subjects.nvik.shortName,
          name: subjects.nvik.name,
          teacher: teachers.Dyachek,
          class: '447',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 3,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.lecture,
          shortName: subjects.engecology.shortName,
          name: subjects.engecology.name,
          teacher: teachers.Brakovich,
          class: '4П',
          korpus: '8',
          subgroup: '0',
        },
      ],
      friday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.vodosnabjenie.shortName,
          name: subjects.vodosnabjenie.name,
          teacher: teachers.Polyakova,
          class: '419',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.practice,
          shortName: subjects.vodosnabjenie.shortName,
          name: subjects.vodosnabjenie.name,
          teacher: teachers.Polyakova,
          class: '14',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 3,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.lecture,
          shortName: subjects.stroyteplfiz.shortName,
          name: subjects.stroyteplfiz.name,
          teacher: teachers.Krutilin,
          class: '5П',
          korpus: '8',
          subgroup: '0',
        },
        {
          id: 4,
          startTime: '13:55',
          endTime: '15:30',
          type: lessonType.practice,
          shortName: subjects.fizra.shortName,
          name: subjects.fizra.name,
          teacher: '',
          class: '',
          korpus: '',
          subgroup: '0',
        },
      ],
      saturday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.teplomasobmen.shortName,
          name: subjects.teplomasobmen.name,
          teacher: teachers.Strytsky,
          class: '453',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.lecture,
          shortName: subjects.teplomasobmen.shortName,
          name: subjects.teplomasobmen.name,
          teacher: teachers.Strytsky,
          class: '453',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 3,
          startTime: '15:40',
          endTime: '17:15',
          type: lessonType.laba,
          shortName: subjects.otoplenie.shortName,
          name: subjects.otoplenie.name,
          teacher: teachers.Volohovich,
          class: '9',
          korpus: '1',
          subgroup: '1',
        },
      ],
    },
    week2: {
      monday: [
        {
          id: 1,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.lecture,
          shortName: subjects.teplustanovki.shortName,
          name: subjects.teplustanovki.name,
          teacher: teachers.Petsuha,
          class: '3П',
          korpus: '8',
          subgroup: '0',
        },
      ],
      tuesday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.stroyteplfiz.shortName,
          name: subjects.stroyteplfiz.name,
          teacher: teachers.Krutilin,
          class: '339',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.teplogenustanovki.shortName,
          name: subjects.teplogenustanovki.name,
          teacher: teachers.Nekalo,
          class: '322',
          korpus: '2',
          subgroup: '2',
        },
        {
          id: 3,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.teplomasobmen.shortName,
          name: subjects.teplomasobmen.name,
          teacher: teachers.Svistun,
          class: '322',
          korpus: '2',
          subgroup: '1',
        },
        {
          id: 4,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.practice,
          shortName: subjects.stroyteplfiz.shortName,
          name: subjects.stroyteplfiz.name,
          teacher: teachers.Krutilin,
          class: '24',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 5,
          startTime: '13:55',
          endTime: '15:30',
          type: lessonType.lecture,
          shortName: subjects.ouis.shortName,
          name: subjects.ouis.name,
          teacher: teachers.Nemkevich,
          class: '339',
          korpus: '1',
          subgroup: '0',
        },
      ],
      wednesday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.practice,
          shortName: subjects.teplomasobmen.shortName,
          name: subjects.teplomasobmen.name,
          teacher: teachers.Svistun,
          class: '21',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.stroyteplfiz.shortName,
          name: subjects.stroyteplfiz.name,
          teacher: teachers.Krutilin,
          class: '14',
          korpus: '1',
          subgroup: '2',
        },
        {
          id: 3,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.laba,
          shortName: subjects.nvik.shortName,
          name: subjects.nvik.name,
          teacher: teachers.Dyachek,
          class: '24',
          korpus: '1',
          subgroup: '1',
        },
        {
          id: 4,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.practice,
          shortName: subjects.tgu.shortName,
          name: subjects.tgu.name,
          teacher: teachers.Karnytsky,
          class: '322',
          korpus: '2',
          subgroup: '0',
        },
      ],
      thursday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.otoplenie.shortName,
          name: subjects.otoplenie.name,
          teacher: teachers.Livansky,
          class: '447',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.lecture,
          shortName: subjects.nvik.shortName,
          name: subjects.nvik.name,
          teacher: teachers.Dyachek,
          class: '447',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 3,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.lecture,
          shortName: subjects.engecology.shortName,
          name: subjects.engecology.name,
          teacher: teachers.Brakovich,
          class: '4П',
          korpus: '8',
          subgroup: '0',
        },
      ],
      friday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.vodosnabjenie.shortName,
          name: subjects.vodosnabjenie.name,
          teacher: teachers.Polyakova,
          class: '419',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.practice,
          shortName: subjects.vodosnabjenie.shortName,
          name: subjects.vodosnabjenie.name,
          teacher: teachers.Polyakova,
          class: '14',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 3,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.lecture,
          shortName: subjects.stroyteplfiz.shortName,
          name: subjects.stroyteplfiz.name,
          teacher: teachers.Krutilin,
          class: '5П',
          korpus: '8',
          subgroup: '0',
        },
        {
          id: 4,
          startTime: '13:55',
          endTime: '15:30',
          type: lessonType.practice,
          shortName: subjects.fizra.shortName,
          name: subjects.fizra.name,
          teacher: '',
          class: '',
          korpus: '',
          subgroup: '0',
        },
      ],
      saturday: [
        {
          id: 1,
          startTime: '8:00',
          endTime: '9:35',
          type: lessonType.lecture,
          shortName: subjects.teplomasobmen.shortName,
          name: subjects.teplomasobmen.name,
          teacher: teachers.Strytsky,
          class: '453',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 2,
          startTime: '9:55',
          endTime: '11:30',
          type: lessonType.lecture,
          shortName: subjects.teplomasobmen.shortName,
          name: subjects.teplomasobmen.name,
          teacher: teachers.Strytsky,
          class: '453',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 3,
          startTime: '11:40',
          endTime: '13:15',
          type: lessonType.practice,
          shortName: subjects.otoplenie.shortName,
          name: subjects.otoplenie.name,
          teacher: teachers.Volohovich,
          class: '21',
          korpus: '1',
          subgroup: '0',
        },
        {
          id: 4,
          startTime: '15:40',
          endTime: '17:15',
          type: lessonType.laba,
          shortName: subjects.otoplenie.shortName,
          name: subjects.otoplenie.name,
          teacher: teachers.Volohovich,
          class: '9',
          korpus: '1',
          subgroup: '2',
        },
      ],
    },
  },
};
